language: python

matrix:
  include:
    # All the versions of Python.
    # NOTE: travis is having conda issues with py2 right now...
    - python: 2.7
    - python: 3.6

git:
    submodules: true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda config --add channels http://ssb.stsci.edu/astroconda
  - conda install --yes pyfftw
  - conda install --yes numpy synphot joblib scipy astropy==2.0.2 pyfftw pysynphot photutils sphinx=1.5.6 bokeh=0.12.6
  - python setup.py develop
